spring.application.name=springweb

spring.cache.type=redis

spring.redis.host=${REDIS_HOST:localhost}
spring.redis.port=${REDIS_PORT:6379}

redis.timeout=2000
redis.maximumActiveConnectionCount=128

spring.main.allow-bean-definition-overriding=true

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always