apiVersion: v1
kind: ServiceAccount
metadata:
  name: backend-sa
  namespace: default

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: backend-job-role
  namespace: default
rules:
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["create", "get", "list", "watch", "delete"]

  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch", "delete"]

  - apiGroups: [""]
    resources: ["pods/log"]
    verbs: ["get"]

  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["create", "get", "delete"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: backend-job-binding
  namespace: default
subjects:
  - kind: ServiceAccount
    name: backend-sa
    namespace: default
roleRef:
  kind: Role
  name: backend-job-role
  apiGroup: rbac.authorization.k8s.io