apiVersion: apps/v1
kind: Deployment

metadata:
  name: backend

spec:
  replicas: 2

  selector:
    matchLabels:
      app: backend

  template:
    metadata:
      labels:
        app: backend

    spec:
      # Backend needs this ServiceAccount to create
      # Kubernetes Jobs and ConfigMaps for code execution.
      serviceAccountName: backend-sa

      containers:
        - name: backend

          image: asia-south1-docker.pkg.dev/cody-gke/cody-repo/backend:latest

          imagePullPolicy: Always

          ports:
            - containerPort: 8080

          env:
            # Redis
            - name: REDIS_HOST
              value: redis

            - name: REDIS_PORT
              value: "6379"

            # MongoDB
            - name: MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: MONGODB_URI

          # Check whether Spring Boot is ready to receive traffic
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080

            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 5

          # Restart the container if the application becomes unhealthy
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080

            initialDelaySeconds: 60
            periodSeconds: 20
            timeoutSeconds: 5
            failureThreshold: 3

          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"

            limits:
              cpu: "1"
              memory: "1Gi"